<script>
export default {
  name: "LicenseVue"
}
</script>

<template>
  <div class="container_main">
    <h1 class="b-feature__title h-ta-c" style="text-align: center;">Terms of use</h1>
    <div class="box-content h-p-0 js-landingpages-blocks-content">
      <p><span style="font-weight: 400;">June «10», 2022<br><br><br></span></p>
      <p style="text-align: center;"><b>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS WEBSITE AND SOFTWARE</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">These Terms of Use are is a legally binding agreement between Limited Liability Partnership <strong>ORDERRY</strong>, a legal entity duly incorporated and existing under the laws of the United Kingdom of Great Britain and Northern Ireland with Registration number <span>OC426588</span> having its address at <span>7 Bell Yard, London, United Kingdom, WC2A 2JR</span>&nbsp;(hereinafter referred to as the “<strong>ORDERRY</strong>”) and You (either an individual or an entity) governing the use of our website at </span><a href="https://remonline.app/">remonline.app</a><span style="font-weight: 400;"> (hereinafter referred to as the “Website”) and “RemOnline” software as defined in paragraph 1.1 of these Terms of Use (hereinafter referred to as the “Software”) accessible through the Website.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">By accessing and browsing the Website and/or by accessing and using the Software You acknowledge that You have read and understood these Terms of Use and agree to be bound by them.</span></p>
      <p style="text-align: center;"><b>! Be aware, if You disagree with these Terms of Use, You must exit this Website and You must not use the Software.</b><b></b></p>
      <h2 style="text-align: justify;"><b>1. DEFINITIONS</b></h2>
      <p style="text-align: justify;"><b>1.1. “RemOnline” software” </b><span style="font-weight: 400;">or the </span><b>“Software”</b><span style="font-weight: 400;"> – it’s a software in form SaaS designed for automation of business processes of service providing companies.</span></p>
      <p style="text-align: justify;"><b>Main functions of the Software:</b></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">CRM system for small and medium-sized businesses,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Order planning and management,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Inventory management and control,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Employee control,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Payroll,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Management Accounting,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Retail Sales control,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Automatic notification for customers and employees,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Calls and telephony in CRM,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Customer base maintaining,&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Barcode creation.</span></li>
      </ol>
      <p style="text-align: justify;"><b>1.2. “SaaS” </b><span style="font-weight: 400;">(Software as a Service) is a software distribution model in which a provider hosts application and makes it available to customers over the Internet.</span></p>
      <p style="text-align: justify;"><b>1.3. “Registration”</b><span style="font-weight: 400;"> means Your completion of the Registration Forms on the Website and provision of Your E-mail, Password and other necessary information. After Registration You become a registered user of the Software.</span></p>
      <p style="text-align: justify;"><b>1.4. “Registration Form” </b><span style="font-weight: 400;">means the set of fields on the Website that You must complete when You sign up for the Software.</span></p>
      <p style="text-align: justify;"><b>1.5. “Login”</b><span style="font-weight: 400;"> means Your e-mail address as indicated by You in the respective field of the Registration Form.</span></p>
      <p style="text-align: justify;"><b>1.6. “Password”</b><span style="font-weight: 400;"> means the unique string of characters entered by You in the respective field of the Registration Form and subsequently used by You, in combination with Your Login, to identify Yourself to the Software.</span></p>
      <p style="text-align: justify;"><b>1.7. “User Account”</b><span style="font-weight: 400;"> – is an established technique for connecting between You as a registered user of the Software and the Software for the purpose of Your authentication to the Software and receival of necessary access to resources of the Software. User account is assigned a username. User account contains Your login, password and other information serving to identify You as the registered user for purposes of the Software use.&nbsp;</span></p>
      <p style="text-align: justify;"><b>1.8. “User Data”</b><span style="font-weight: 400;"> means any data, information or material created, provided, submitted or uploaded by You in the course of using the Software except Your personal data submitted during the process of filling out the Registration Forms. For more information how we process personal data, please read our Privacy Policy published at </span><a href="/privacy-policy/">remonline.app/privacy-policy</a><span style="font-weight: 400;">. Except as otherwise expressly provided in these Terms of Use, RemOnline will not access, monitor, review, use, publish, reproduce or disclose any of Your User Data.</span></p>
      <p style="text-align: justify;"><b>1.9. “Trial Period” – </b><span style="font-weight: 400;">is an established period when the Software has been made available to You free of charge for evaluation (trial) purposes.&nbsp;</span></p>
      <p style="text-align: justify;"><b>1.10. “Subscription Period”</b><span style="font-weight: 400;"> – is an established prepaid range of time not less than one calendar month during which You can use the Software.</span></p>
      <p style="text-align: justify;"><b>1.11. “Subscription Scope” </b><span style="font-weight: 400;">– is a prepaid quantity of end-users that will be able to use the Software on behalf of Your entity during the Subscribed period.</span></p>
      <p style="text-align: justify;"><b>1.12. “Subscription Fee” </b><span style="font-weight: 400;">– is an established price for use of the Software as indicated in Schedule of fees published at </span><a href="/pricing/">remonline.app/pricing</a>&nbsp;<span style="font-weight: 400;">that is an integral part of these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>1.13. “Territory”</b> <b>of the Software use</b><span style="font-weight: 400;"> – is all countries of the World except countries with trade and other restrictions according to the applicable law.</span></p>
      <p style="text-align: justify;"><b>1.14. “Purpose”</b> <b>of the Software use</b><span style="font-weight: 400;">– is for Your internal business use.</span></p>
      <p style="text-align: justify;"><strong><b>1.15.</b> <b>"Recurring Payment"</b><span style="font-weight: 400;"> is a payment made automatically using a saved payment method.</span></strong></p>
      <h2 style="text-align: justify;"><b>2. SUBJECT MATTER</b></h2>
      <p style="text-align: justify;"><b>2.1.</b><span style="font-weight: 400;"> On terms and conditions determined in these Terms of Use RemOnline grants You the non-exclusive non-transferable right to use the Software and Website in the Territory and for the Purpose as set forth herein and You agree to use the Software and Website as prescribed hereby and pay Subscription Fee for such use.&nbsp;</span></p>
      <p style="text-align: justify;"><b>2.2.</b><span style="font-weight: 400;"> Full and general acceptance of these Terms of Use is Your registration.<br></span><span style="font-weight: 400;">IF YOU DO NOT WISH TO ACCEPT THESE TERMS OF USE AS STATED, THEN RemOnline IS UNWILLING TO GRANT THE RIGHT TO USE OF THE SOFTWARE TO YOU; IN WHICH EVENT, YOU MUST SELECT THE "I DISAGREE" OPTION AND/OR CLICK THE "CANCEL" BUTTON, WHEREUPON THE REGISTRATION WILL NOT COMPLETE.</span></p>
      <p style="text-align: justify;"><b>2.3.</b><span style="font-weight: 400;"> All rights not specifically granted in these Terms of Use are reserved to RemOnline and/or its third party licensor(s). These Terms of Use do not grant You any Intellectual Property Rights in connection with the Software or rights to any trademarks of RemOnline.</span></p>
      <p style="text-align: justify;"><b>2.4.</b><span style="font-weight: 400;"> These Terms of Use may be amended from time to time. Any amendments to these Terms of Use (amendment Term of Use) shall take effect immediately on posting on the Website, unless otherwise stated in these Terms of Use. Your access to and browsing of the Website and/or Your continued access to and use of the Software (or any portion thereof) after any such amendments have been made constitutes Your acceptance of the amended Terms of Use. Therefore, You should review these Terms of Use on a regular basis.</span></p>
      <p style="text-align: justify;"><b>2.5.</b><span style="font-weight: 400;"> Your failure to comply with or usage of the Software outside of these Terms of Use shall entitle RemOnline to terminate these Terms of Use and, accordingly, to cease Your access to and use of the Software.</span></p>
      <h2 style="text-align: justify;"><b>3. THE SOFTWARE USE</b></h2>
      <p style="text-align: justify;"><b>3.1.</b><span style="font-weight: 400;"> You shall use the Software strictly for the Purpose, only within the Territory, during the Trial Period and (or) Subscription Period and within the Subscription Scope.</span></p>
      <p style="text-align: justify;"><b>3.2.</b><span style="font-weight: 400;"> The right to use the Software commences:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">from the moment of Your registration – for Trial Period,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">from the moment of payment of Subscription Fee – for the Subscription Period.&nbsp;</span></li>
      </ol>
      <p style="text-align: justify;"><b>3.3. </b><span style="font-weight: 400;">The right to use the Software terminates:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">at the last second of the last day of established Trial Period – for Trial Period,</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">at the last second of the last day of the Subscription Period – for the Subscription Period.&nbsp;</span></li>
      </ol>
      <p style="text-align: justify;"><b>3.4. Please, be aware: </b><span style="font-weight: 400;">After Your registration all actions carried out by using Your Login and Password shall be considered as actions carried out by You personally. </span><span style="font-weight: 400;">Licensee's use of the License is confirmed by logging into the Software using Licensee's Login and Password during the Subscription Period.&nbsp;</span></p>
      <p style="text-align: justify;"><b>3.5. </b><span style="font-weight: 400;">You may use the Software and any results obtained through the use of the Software solely for lawful purposes.&nbsp;</span></p>
      <p style="text-align: justify;"><b>3.6. </b><span style="font-weight: 400;">You may not either directly or indirectly:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">sell, rent, lease, sublicense, lend, assign, time-share, or transfer, in whole or in part, or provide third parties access to prior or present versions of the Software or any updates;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">decompile, reverse engineer, disassemble or otherwise reduce any part of the Software to human-readable form nor permit any third party to do so;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">copy, make error corrections to or otherwise modify or adapt or translate the Software nor create derivative works based upon the Software nor permit a third party to do so;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">remove or obscure any copyright, trademark notice, or restrictive legend of RemOnline or its third party licensor(s) nor permit a third party to do so;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">create, upload or publish in any other way, any materials which are illegal, harmful, threatening, offensive or libelous; which infringe the copyright of a third party; which incite hatred and/or discrimination based on race, ethnicity, gender or social status; which contain pornography; which violate the rights of a third party or incite others to violate the rights of a third party; which defame any persons or discredit the good name and reputation of their business; which violate the rights of minors and/or are damaging to minors in any way; or any other similar materials;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">impersonate another person or a representative of an organization, including RemOnline employees and forum moderators, or make misleading statements about the properties and characteristics of any subjects or objects;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">create, upload or publish in any other way, materials which You are not allowed to make public under applicable laws, treaties or regulations, including personal or confidential data, or which violate applicable laws, treaties or regulations;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">collect information from or interact with the Software by means of automated scripts or software not explicitly provided by RemOnline;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">use other users’ logins and passwords to sign in to the Software;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">collect and store personal data of other users of the Software;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">disrupt the normal operation of the Software;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">register one user under multiple User Accounts;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">register with the Software anyone other than Yourself;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">share Your Password with other people or let anyone else use the Software under Your Login and Password or otherwise compromise the security of Your Software credentials.</span></li>
      </ol>
      <p style="text-align: justify;"><b>3.7. </b><span style="font-weight: 400;">You assume full responsibility for and all risks arising from Your use of the Software.</span></p>
      <p style="text-align: justify;"><b>3.8.</b><span style="font-weight: 400;"> You assume the RemOnline shall not and will not check the information (data) created, uploaded or published in any other way by You within the Software use and will not bear responsibilities for such Your data.</span></p>
      <h2 style="text-align: justify;"><b>4. PRICES AND PAYMENTS. REFUND POLICY</b></h2>
      <p style="text-align: justify;"><b>4.1. Prices and payments&nbsp;</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.1 To use the Software (except usage within the Trial Period) You must pay a Subscription Fee to the amount and in the payment procedure, determined in the Schedule of fees published at </span><a href="/pricing/">remonline.app/pricing</a><span style="font-weight: 400;">.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.2 After the expiration of Your Subscription Period, the functionality of the Software will be no longer available or will be limited until You make a payment to renew Your subscription.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp;4.1.2.1 If You make the payment after the expiration of Your Subscription Period, the date of payment is considered as the renewal day and marks the beginning of the renewed Subscription Period.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp;4.1.2.2 If You make the payment before the expiration of Your Subscription Period, the date following the last day of Your subscription marks the beginning of the renewed Subscription Period.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.3 The payments shall be considered made at the date the funds are credited to the RemOnline’s account.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.4 All fees charged by the bank and (or) other financial institutions / other third parties in the course of payment shall be paid by the paying Party.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.5 If the currency of Your bank account or payment system is not the same as the currency in which the Software is priced, all currency conversions will be made at the exchange rate of Your bank or payment system.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.1.6 RemOnline may, in its sole discretion, change the prices and the payment procedure at any time. Therefore, You should review regularly the prices and the payment procedure in the Schedule of fees published at </span><a href="/pricing/">remonline.app/pricing</a><span style="font-weight: 400;">.</span></p>
      <p style="text-align: justify;"><b>4.2. Refund policy</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.2.1 RemOnline guaranties to You the possibility of a full refund of the money paid as the first payment of the license fee within 14 (fourteen) calendar days from the date of payment, by sending an e-mail about early termination of this Terms of Use and return of the money paid as an advance payment from the registered e-mail of the Licensee to the e-mail of the Licensor: </span><span style="font-weight: 400;">help@RemOnline.com</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">After 14 (fourteen) calendar days from the date of payment, there is no refund for the service provided and used.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.2.2 RemOnline shall revise Your request on early termination of these Terms of Use and return of advance paid funds and shall return the money to Your account, from which funds were debited, within thirty (30) calendar days from the date of the request receiving.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.2.3 In any case, unless expressly stated otherwise payments for the SMS service are non-refundable.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.2.4 The refund of fee means that these Terms of Use are early terminated and, accordingly, Your use of the Software shall be terminated.</span></p>
      <p style="text-align: justify;"><b>4.3. Recurring payment</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.3.1. A Recurring payment shall be made if the Licensee chooses to pay for the license by credit card.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.3.2. A Recurring payment shall be activated by the Licensee automatically at the first payment. In the future the Licensor will make a Recurring payment and renew the license for a period which is the same as the last license period paid by the Licensee.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.3.3. The Licensee can manage the settings of the Recurring payment (activate, deactivate, change the license renewal period and other options) in the Program settings.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.3.4. The Licensor will make a Recurring payment and renew the license according to the Recurring payment settings on the last day of the license validity term.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">4.3.5. In case the Licensor fails to make a Recurring payment using the saved payment method, and the Licensee did not make payment by himself before the license expired, the Grace Period begins, during which the Licensor attempts to make a Recurring payment. </span><span style="font-weight: 400;">In any case, unless clearly stated otherwise, Recurring Payments are not refundable. The procedure for connecting and disconnecting recurring payments is described in clause 4.3 of these Terms of Use.</span></p>
      <h2 style="text-align: justify;"><b>5. PARTIES’ RIGHTS AND OBLIGATIONS</b></h2>
      <p style="text-align: justify;"><b>5.1.</b> <b>RemOnline is entitled to:</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.1 modify the Software at any time and in its sole discretion, including all resources and materials available on the Website;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.2 take in its sole discretion any or all of the following actions:&nbsp;</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">suspend Your Login and Password,&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">delete any of Your User Data,&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">reject any of Your User Data that You may be attempting to upload to the Software,&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">permanently terminate Your access to and use of the Software&nbsp;</span></li>
      </ol>
      <p style="text-align: justify;"><span style="font-weight: 400;">if RemOnline in its sole discretion determines that You are engaged in, or intend to engage in, any activities that are in breach of Your obligations under paragraphs 5.3 or 5.4 of these Terms of Use; or any activities aimed at disrupting the operation of the Software; or any activities aimed at publishing information that is in breach of these Terms of Use and/or applicable laws or is false and discredits RemOnline’s good name and reputation; or any other activities that are damaging to RemOnline or other users of the Software; or that You have asked other users to engage in any of the aforementioned activities;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.3 interrupt Your access to and use of the Software at any time without prior notice under the following reasons, including, but not limited to: maintenance work, circumstances beyond the reasonable control of RemOnline, crashes of software or hardware owned by third parties, or malicious actions by third parties aimed at disrupting the operation of the Software;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.4 in its sole discretion add new features to the Software, remove existing features or modify the design of existing features;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.5 delete User Data one (1) year after the date of expiration of Your rights to use the Software;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.6 disclose User Data in response to requests from law enforcement or other regulatory authorities or in response to a subpoena or other legal process.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">RemOnline may disclose Your User Data as RemOnline believes necessary or appropriate:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to comply with applicable law, including laws outside Your country of residence;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to respond to requests from public and government and other authorities, including such authorities outside Your country of residence;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to protect RemOnline’s rights and/or those of You or others, including in cases of fraud and infringement of Intellectual Property Rights;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to comply with prudent legal practice as determined by RemOnline and with applicable law or legal processes;&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to limit the damages that RemOnline may sustain; and&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">to provide the Software to You.</span></li>
      </ol>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.7 publish on the Website advertisements and any other content permitted by applicable laws;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.1.8 request any information proved Your compliance with the terms of these Terms of Use and (or) the information necessary for the proper fulfillment of these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>5.2.</b> <b>RemOnline shall:</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.2.1 provide a daily non-stop access to the Software, except as specified herein;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.2.2 do their best to ensure the confidentiality and the safety of User Data in accordance with these Terms of Use and with the Privacy Policy;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.2.3 adjust any failures in the Software, caused by the fault of the RemOnline within a reasonable time;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.2.4 carry out maintenance work as possible at night and on weekends;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.2.5 back up regularly Your data and information.</span></p>
      <p style="text-align: justify;"><b>5.3.</b> <b>You are entitled to:</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.1 use the Software in accordance with these Terms of Use;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.2 upload any User Data created by You within the Software use before it will be automatically deleted by the Software as set forth in paragraph 5.1.5 of these Terms of Use;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.3 cancel Your subscription at any time by contacting RemOnline. If You cancel Your subscription, You will be able to continue using the Software until the end of Your Subscription Period. All payments are non-refundable unless otherwise is specified in a paragraph 4.2 of these Terms of Use;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.4 early terminate these Terms of Use on terms and procedures, as specified in a paragraph 4.2 of these Terms of Use;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.5 request for technical assistance and support during the Subscription Period;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.3.6 inform RemOnline by writing to the e-mail address specified in paragraph 9.9 of these Terms of Use in case You discover any information that violates applicable laws or Your rights thereunder or any information that You find offensive or defamatory or otherwise damaging to You.</span></p>
      <p style="text-align: justify;"><b>5.4.</b> <b>You shall:</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.4.1 register with the Software by completing the Registration Forms and provide Your correct information on the Registration Forms. RemOnline shall not be liable for any breach of these Terms of Use as a result of an incorrect information provided by You on the Registration Forms;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.4.2 be solely responsible for the safekeeping of Your Password and for any actions performed under Your Login and Password. You shall immediately notify RemOnline of any instances of unauthorized access to the Software under Your Login and Password and/or of any other security breach that You become aware of;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.4.3 be responsible for the accuracy, quality, integrity, legality, reliability, and appropriateness, intellectual property ownership, and right to use with respect to all of Your User Data and any data sent by You to the Software. You will abide by, and will be solely responsible for any breach of, applicable local, state, national and foreign laws, treaties, and regulations in connection with Your User Data, including those related to data privacy, international communications, and the transmission of technical or personal data. You shall defend, indemnify, and hold harmless RemOnline and its subsidiaries, affiliates, directors, officers, employees, agents, and representatives from and against any and all claims, actions, proceedings, expenses, liabilities, damages, costs, and expenses, including attorneys’ fees, associated with or arising from uploading or using Your User Data;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.4.4 pay the Subscription Fee in the amount and within the time limits set forth herein. RemOnline shall not bear responsibility for interruption of Your access to and use of the Software because of payment delay</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">5.4.5 review these Terms of Use as well as Schedule of fees and Privacy Policy on a regular basis. Your continued access to and use of the Software (or any portion thereof) after any such amendments have been made constitutes your agreement to amended Terms of Use.</span></p>
      <h2 style="text-align: justify;"><b>6. LIMITATION OF LIABILITY</b></h2>
      <p style="text-align: justify;"><b>PLEASE READ THIS SECTION CAREFULLY. THIS SECTION LIMITS RemOnline’S LIABILITY TO YOU FOR ISSUES THAT MAY ARISE IN CONNECTION WITH YOUR ACCESS TO AND USE OF THE SOFTWARE</b><b><i>.</i></b></p>
      <p style="text-align: justify;"><b>6.1.</b><span style="font-weight: 400;"> RemOnline shall not provide You with an Internet connection or with any hardware or software required to connect to the Internet, and RemOnline shall not be liable for the quality of Your Internet connection or the quality of the hardware or software that You use to connect to the Internet. RemOnline shall not be liable for any malfunction or other problems in telephone networks or software, computer systems, servers, providers, computer hardware, software or telecom equipment, or for any malfunction in the operation of e-mail software and scripts, howsoever caused.</span></p>
      <p style="text-align: justify;"><b>6.2.</b><span style="font-weight: 400;"> You acknowledge that Your information will be transmitted over an unsecured public computer network and that RemOnline shall not be liable for any loss of information transmitted in this manner.</span></p>
      <p style="text-align: justify;"><b>6.3.</b><span style="font-weight: 400;"> RemOnline shall not be liable for any delay, malfunction, missed or late delivery, removal or loss of any of Your User Data.</span></p>
      <p style="text-align: justify;"><b>6.4.</b><span style="font-weight: 400;"> RemOnline DOES NOT REPRESENT OR WARRANT THAT:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">YOUR USE OF THE SOFTWARE WILL BE SECURE OR ERROR-FREE OR THAT THE SOFTWARE WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">ANY ERRORS OR DEFECTS WILL BE CORRECTED;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">THE SOFTWARE OR THE SERVER(S) THAT MAKE THE SOFTWARE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</span></li>
      </ol>
      <p style="text-align: justify;"><b>6.5. THE SOFTWARE IS PROVIDED BY RemOnline ON AN “AS IS” BASIS. ALL CONDITIONS, REPRESENTATIONS, AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS ARE HEREBY DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</b></p>
      <p style="text-align: justify;"><b>6.6. IN NO EVENT WILL RemOnline BE LIABLE FOR ANY BUSINESS INTERRUPTION, LOSS OF DATA OR INFORMATION OF ANY KIND, BUSINESS OR OTHERWISE, OR FOR LOST PROFITS OR LOST REVENUE, OR FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR PUNITIVE DAMAGES, WHETHER IN CONTRACT, TORT OR OTHERWISE, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF YOUR ACCESS TO AND USE OF, OR INABILITY TO USE, THE SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. RemOnline’S MAXIMUM AGGREGATE LIABILITY UNDER OR IN CONNECTION WITH THESE TERMS OF USE SHALL BE LIMITED TO THE SUM EQUAL TO YOUR SUBSCIPTION FEE, PAYED TO THE RemOnline FOR CURRENT (LAST) MONTH OF SUBSCRIPTION.</b></p>
      <p style="text-align: justify;"><b>6.7.</b><span style="font-weight: 400;"> To the extent permitted by law, RemOnline excludes all conditions, warranties, representations or other terms which may apply to the use of the Software, whether express or implied.</span></p>
      <p style="text-align: justify;"><b>6.8.</b><span style="font-weight: 400;"> In no event shall RemOnline, nor any of its officers, directors, employees, representatives, subsidiaries, affiliated companies, distributors, resellers, affiliate partners, licensees, licensors, agents or others involved in creating, sponsoring, promoting or otherwise making the Website and the Software available take any responsibility or accept any liability for:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">direct, indirect, punitive, incidental, special or consequential loss arising from or in any way connected with Your use or inability to use of the Website and the Software (including, but not limited to, Your reliance upon the content displayed on the Website, including any reviews and opinions appearing on the Website);</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">any inaccuracy, errors or incompleteness relating to any of the information available on the Website;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">any computer viruses, information, software, linked sites, products, and software obtained through the Website; or otherwise arising out of the access to, display of or use of the Software.</span></li>
      </ol>
      <p style="text-align: justify;"><b>6.9.</b><span style="font-weight: 400;"> RemOnline is under no obligation to review any materials or information that You may create, upload and/or send by e-mail or transmit in any other way in the course of using the Software.</span></p>
      <p style="text-align: justify;"><b>6.10.</b><span style="font-weight: 400;"> RemOnline does not warrant that such materials or information are accurate, true, complete, timely, and of good quality, or that they will meet Your needs and requirements. RemOnline assumes no responsibility for such materials or information.</span></p>
      <p style="text-align: justify;"><b>6.11.</b><span style="font-weight: 400;"> RemOnline assumes no responsibility for any User Data uploaded by You and/or other users of the Software.</span></p>
      <h2 style="text-align: justify;"><b>7. COPYRIGHTS AND TRADEMARKS</b></h2>
      <p style="text-align: justify;"><b>7.1.</b><span style="font-weight: 400;"> All the materials available on the Website, the appearance, organization, and layout of the Website and the Software are subject to trademark, copyright, and database rights and other registered and unregistered Intellectual Property Rights, which are owned either directly by RemOnline or by its licensors, suppliers or providers.</span></p>
      <p style="text-align: justify;"><b>7.2.</b><span style="font-weight: 400;"> All the RemOnline trademarks are the intellectual property of RemOnline and are provided only for reference. RemOnline does not grant You any rights to use these trademarks.</span></p>
      <p style="text-align: justify;"><b>7.3.</b><span style="font-weight: 400;"> The Software may contain may include links to other websites or services (“Linked Sites”) or integrations with other services solely as a convenience to Users. Furthermore, RemOnline makes no express or implied warranties with regard to the information, material, products, services and policies (including privacy and cookies policies) that are contained on or accessible through Linked Sites. YOU ACCESS TO AND USE OF LINKED SITES, INCLUDING THE INFORMATION, MATERIAL, PRODUCTS, SERVICES AND POLICIES ON LINKED SITES OR AVAILABLE THROUGH LINKED SITES, IS SOLELY AT YOUR OWN RISK.</span></p>
      <p style="text-align: justify;"><b>7.4.</b><span style="font-weight: 400;"> No Intellectual Property Rights belonging to RemOnline (including but not limited to the Software and any RemOnline’s patents, trademarks, or copyrights) are transferred to You under these Terms of Use. You shall not, in any way, during or after the termination of these Terms of Use, make any use of or claim any right to any name, logo, trademark, pattern or design owned by RemOnline, or any name, logo, trademark, pattern or design resembling them.</span></p>
      <p style="text-align: justify;"><b>7.5.</b><span style="font-weight: 400;"> No Intellectual Property Rights belonging to You are transferred to RemOnline under these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>7.6.</b><span style="font-weight: 400;"> The Software contains valuable trade secrets and confidential information belonging to RemOnline and third parties that are protected by international treaty provisions and/or applicable laws.</span></p>
      <p style="text-align: justify;"><b>7.7.</b><span style="font-weight: 400;"> All title and rights in and to the content that is not contained in the Software, but may be accessible through the use of the Software, are the property of the respective content owners and may be protected by applicable copyright or other intellectual property laws and international treaties. These Terms of Use do not grant You any rights to such intellectual property.</span></p>
      <h2 style="text-align: justify;"><b>8. GOVERNING LAW AND DISPUTE SETTLEMENT</b></h2>
      <p style="text-align: justify;"><b>8.1.</b><span style="font-weight: 400;"> These Terms of Use shall be subject to and construed and interpreted in accordance with the Laws of England and Wales without reference to any conflict of laws principles and shall be subject to the exclusive jurisdiction of the Courts of England and Wales.</span></p>
      <p style="text-align: justify;"><b>8.2.</b><span style="font-weight: 400;"> It is hereby agreed that the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded if and to the extent that it applies to these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>8.3.</b><span style="font-weight: 400;"> Disputes between the Parties shall be resolved in accordance with the procedure, established by the Laws of England and Wales.</span></p>
      <p style="text-align: justify;"><b>8.4.</b><span style="font-weight: 400;"> Whatever the case, it is hereby agreed that the Parties will endeavor to resolve all possible disputes and disagreements that may arise under these Terms of Use or in connection with them through negotiations. </span></p>
      <h2 style="text-align: justify;"><b>9. MISCELLEANOUS</b></h2>
      <p style="text-align: justify;"><b>9.1. Personal Data</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">You acknowledge and agree that the usage of any Personal Data You may provide or that RemOnline may collect from You in connection with the Software is governed by the RemOnline Privacy Policy published at </span><a href="/privacy-policy/">remonline.app/privacy-policy</a><span style="font-weight: 400;">. These Terms of Use do not apply to the processing of Personal Data.</span></p>
      <p style="text-align: justify;"><b>9.2.</b> <b>Assignment of rights and obligations</b><span style="font-weight: 400;">&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">RemOnline may transfer and assign any of its rights and obligations hereunder to a third party at any time without notice to You and without Your consent.</span></p>
      <p style="text-align: justify;"><b>9.3.</b> <b>Indemnification</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">You shall defend, indemnify, and hold RemOnline and its affiliates harmless from and against any actual or threatened third-party claim arising out of or based upon:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">usage of Your User Data;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Your negligence or willful misconduct;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Your breach of these Terms of Use;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">any breach by persons acting on Your behalf who access and use the Software using Your Login and Password.</span></li>
      </ol>
      <p style="text-align: justify;"><span style="font-weight: 400;">You shall pay:</span></p>
      <ol style="text-align: justify;">
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">all damages, costs, and attorneys’ fees awarded against RemOnline in any proceeding under this paragraph;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">all out-of-pocket costs (including reasonable attorneys’ fees) reasonably incurred by RemOnline in connection with the defense of such proceeding (other than attorneys’ fees and costs incurred without Your consent after You have accepted defense of such claim);&nbsp;</span></li>
        <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">if any proceeding arising under this paragraph is settled, You will pay all amounts agreed to by You in the settlement of any such claims.</span></li>
      </ol>
      <p style="text-align: justify;"><span style="font-weight: 400;">The provisions of this paragraph shall survive the termination of Your use of the Software or the expiration of Your subscription to the Software.</span></p>
      <p style="text-align: justify;"><b>9.4.</b> <b>Force Majeure</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">RemOnline will not be liable for or will be considered to be in breach of or in default under these Terms of Use on account of any delay or failure to perform as required by these Terms of Use as a result of any cause or condition beyond RemOnline’s reasonable control.</span></p>
      <p style="text-align: justify;"><b>9.5.</b> <b>Waiver</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">The failure of either party to comply with any provision of these Terms of Use shall not constitute a waiver of such provision unless accompanied by a clear written statement that such provision is waived. A waiver of any default hereunder or of any of the provisions of these Terms of Use shall not be deemed to be a continuing waiver or a waiver of any other default or of any other provision, but shall apply solely to the instance to which such waiver is directed. Except as expressly provided herein to the contrary, the exercise of any right or remedy provided in these Terms of Use shall be without prejudice to the right to exercise any other right or remedy provided by law or equity.</span></p>
      <p style="text-align: justify;"><b>9.6.</b> <b>Severability</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">If any provision of these Terms of Use is determined to be illegal, unenforceable or invalid, such provision shall nonetheless be enforced to the fullest extent permitted by applicable law, and such determination shall not affect the legality, validity or enforceability of the remaining provisions.</span></p>
      <p style="text-align: justify;"><b>9.7.</b> <b>Interpretation</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">The section headings contained in these Terms of Use have been inserted for identification and reference purposes only and shall not be used to construe or interpret these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>9.8.</b> <b>Entire Terms of Use</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">These Terms of Use constitute the final and complete expression of the Terms of Use between You and RemOnline regarding Your access to and use of the Software. These Terms of Use supersede all previous oral and written communications regarding these matters, including any marketing materials or documentation provided by RemOnline prior to or after the execution of these Terms of Use, unless specifically referred to and incorporated into these Terms of Use. No employee, agent or other representative of RemOnline has any authority to bind RemOnline with respect to any statement, representation, warranty or other expression unless the same is specifically set forth in these Terms of Use. No usage of trade or other regular practice or method of dealing between the parties will be used to modify, interpret, supplement or alter these Terms of Use.</span></p>
      <p style="text-align: justify;"><b>9.9.</b> <b>Contact information</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">You may contact RemOnline at this e-mail address: <span>support@remonline.app</span></span><span style="font-weight: 400;">&nbsp;or support chat inside Software.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">RemOnline may contact You at the e-mail address provided by You on the Registration Forms when registering with the Software.</span></p>
    </div>
  </div>
</template>

<style scoped>

</style>