<script>
export default {
  name: "PolicyVue"
}
</script>

<template>
  <div class="container_main">
    <h1 class="b-feature__title h-ta-c" style="text-align: center;">Privacy Policy RemOnline</h1>
    <div class="box-content h-p-0 js-landingpages-blocks-content">
      <p><span style="font-weight: 400;">June «10», 2022</span></p>
      <p><span style="font-weight: 400;">&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">This Statement is the Privacy Policy (hereinafter referred to as the "Policy") of the Limited Liability Partnership</span> <span style="font-weight: 400;">ORDERRY, </span><span style="font-weight: 400;">a legal entity duly incorporated and existing under the laws of United Kingdom Great Britain and Northern </span><span style="font-weight: 400;">Ireland with Registration number OC426588</span> <span style="font-weight: 400;">having its address at </span><span style="font-weight: 400;">7 Bell Yard, London, United Kingdom, WC2A 2JR</span> <span style="font-weight: 400;">(hereinafter referred to as the "ORDERRY" or "we" or "us") is designed by ORDERRY to explain how we collect, store, transfer and use (hereinafter </span><span style="font-weight: 400;">collectively </span><span style="font-weight: 400;">referred to as the “</span><span style="font-weight: 400;">process</span><span style="font-weight: 400;">” or </span><span style="font-weight: 400;">“processing”) </span><span style="font-weight: 400;">Your personal data, and which rights and options You have in this respect.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We process Your personal data</span><span style="font-weight: 400;"> in connection with Your </span><span style="font-weight: 400;">use of our website </span><a href="https://remonline.app/">remonline.app</a> <span style="font-weight: 400;">(hereinafter referred to as the “Website”) and “ORDERRY” software as defined in paragraph 1.1 of </span><a href="/agreement/"><span style="font-weight: 400;">Terms of Use</span></a><span style="font-weight: 400;"> (hereinafter referred to as the “Software”).</span><b></b></p>
      <p style="text-align: center;"><b>! Be aware, if You disagree with this Privacy Policy, You must exit the Website and You must not use the Software.</b></p>
      <p style="text-align: center;"><b>By continuing to use the Website and (or) the Software, You give us a consent to process Your personal data in accordance with this Privacy Policy.</b><b></b></p>
      <h2 style="text-align: justify;"><b>GDPR Compliance</b></h2>
      <p style="text-align: justify;"><span style="font-weight: 400;">We comply with the principles established by the Data Protection Act 2018 (Act) accordingly incorporating the EU General Data Protection Regulation (GDPR).&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We as a “data controllers” guaranty hereby that Your personal information:</span></p>
      <ol style="list-style-type: lower-alpha; text-align: justify;">
        <li><span style="font-weight: 400;">is processed legally, honestly and transparently;</span></li>
        <li><span style="font-weight: 400;">is collected for certain, explicit and legitimate purposes and is not processed further in a way that is incompatible with these purposes ("purposes limitation");</span></li>
        <li><span style="font-weight: 400;">is adequate, appropriate and limited to what is necessary for the purposes for which it is processed ("data minimization");</span></li>
        <li><span style="font-weight: 400;">is accurate and, if necessary, updated. Every reasonable step is taken to ensure that personal data which was inaccurate, considering the purposes for which it has been processed, was erased or corrected without delay ("accuracy");</span></li>
        <li><span style="font-weight: 400;">is stored in a form that allows identification of Users no longer than it is necessary for the purposes for which personal data is processed ("limitation of storage");</span></li>
        <li><b><span style="font-weight: 400;">is processed in a way that provides proper protection of personal data, including protection from unauthorized or illegal processing, as well as from accidental loss, destruction or damage using appropriate technical and/or organizational measures ("integrity and confidentiality").</span></b></li>
      </ol>
      <p style="text-align: justify;">&nbsp;</p>
      <p style="text-align: justify;"><b>Personal data types which is collected and processed by ORDERRY in respect of You and ways of it process:</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">The types of personal data relating to You, that we may process, depends on Your interaction with us. The key types of personal data that we may process are set out below.</span></p>
      <h2 style="text-align: justify;"><b>Personally identifying information</b></h2>
      <p style="text-align: justify;"><span style="font-weight: 400;">As used herein, the term </span><span style="font-weight: 400;">personally identifying information</span> <span style="font-weight: 400;">generally means information that specifically identifies an individual (such as user's name, address, telephone number, e-mail address, credit card or other account number or geophysical location) or that is associated with an identifiable person (such as demographic information or information about a person's activities when such information is linked to personally identifying information).&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">P</span><span style="font-weight: 400;">ersonally identifying information</span> <span style="font-weight: 400;">does not include "aggregate" information, which is data we collect about the use of the Website and Software or about categories of users of our Website and Software, from which any </span><span style="font-weight: 400;">personally identifying information</span> <span style="font-weight: 400;">has been removed. This Policy in no way limits or restricts our collection of aggregate information.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We do not collect any p</span><span style="font-weight: 400;">ersonally identifying information</span> <span style="font-weight: 400;">from mere visitors of the Website. But when You send us an email, or communicate with us in any other way (for example consult with our sales, support and (or) marketing teams) and when You sign up for our Software You are voluntarily giving us Your p</span><span style="font-weight: 400;">ersonally identifying information</span><span style="font-weight: 400;">: email address, telephone number</span><b>, </b><span style="font-weight: 400;">name, and possibly job title, practice area, location, employer information.</span></p>
      <p style="text-align: justify;"><b>By giving us this p</b><b>ersonally identifying</b> <b>information, You agree to this information being collected, used, disclosed, transferred within the United Kingdom and European Union (to our data storage centre in Netherlands) and stored by us, as described in this Privacy Policy.</b></p>
      <p style="text-align: justify;"><b>We use Your p</b><b>ersonally identifying </b><b>information:</b></p>
      <ol style="list-style-type: lower-alpha; text-align: justify;">
        <li><span style="font-weight: 400;">to manage, administer, monitor the use and improve of our Software;</span></li>
        <li><span style="font-weight: 400;">to manage and administer our Software users;</span></li>
        <li><span style="font-weight: 400;">to provide information and support requested by You;</span></li>
        <li><span style="font-weight: 400;">to promote our Software, including by sending to You updates, advertising and other marketing materials;</span></li>
        <li><span style="font-weight: 400;">to fulfil our Terms of Use and protect our legal rights;</span></li>
        <li><span style="font-weight: 400;">to comply with and enforce legal requirements;</span></li>
      </ol>
      <p style="text-align: justify;"><span style="font-weight: 400;">We also reserve the right to contact You if compelled to do so as part of a legal proceeding or if there has been a violation of any applicable licensing, warranty and purchase agreements.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">All data which is provided by You must be correct and valid. You are solely responsible for the accuracy, completeness and correctness of the data which You provide.</span></p>
      <p style="text-align: justify;"><b>Personal data from minors</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">ORDERRY’S Website and Software are directed solely at adults. If You are under the age of sixteen, please do not provide us with any of Your personal data, including Your email address.</span></p>
      <p style="text-align: justify;"><b>Aggregate information</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">When You browse our Website, we may collect information about Your visit to our Website and Your web browsing. That information may include Your IP address, Your operating system, Your browser ID, Your browsing activity, and other information about how You interacted with our Website. We may collect this information as a part of log files as well as through the use of cookies or other tracking technologies.&nbsp;</span></p>
      <p style="text-align: justify;"><b>IP address lookup</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We use third parties to provide information about visitors to our Website. When You visit our Website we will record Your IP address. This address will be matched against public and proprietary IP address databases to provide us with information about Your visit. This information may identify the organization to whom the IP address is registered but not individuals. In some limited cases, i.e. single person companies, individual entrepreneurs, it may be possible to identify personal data from publicly available ICANN data.</span></p>
      <p style="text-align: justify;"><b>Cookies, tracking &amp; beacons</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may use various technologies to collect and store information when You use our Website and the Software, and this may include using cookies and similar tracking technologies, such as pixels and web beacons, to analyse trends, administer the Website and the Software, track users’ movements around the Website and the Software, serve targeted advertisements, and gather demographic information about our user base as a whole.</span></p>
      <p style="text-align: justify;"><b><i>Cookies/tracking:</i></b><span style="font-weight: 400;"> Cookies allow us to provide important site functionality, so You don’t have to re-enter lots of information. They also allow us to remember what links and pages have been clicked or viewed during a session. The types of cookies that we use are referred to as "session" cookies and "persistent" cookies. Session cookies are temporary and are automatically deleted once You leave the Website. Persistent cookies remain on Your computer hard drive until You delete them.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">If You have provided us with personal data – completing a contact form, for example – we may associate this personal data with other information. This will allow us to identify and record what is most relevant to You.&nbsp;</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">By using Your browser controls, You are always in control of the cookies we store and access on Your computer. Users can also control the use of cookies at the individual browser level. If You wish to block, erase, or be warned of cookies, please refer to Your browser instructions or help screen to learn about these functions. However, if Your browser is set not to accept cookies or if a user rejects a cookie,</span><span style="font-weight: 400;"> that may negatively impact Your use of or Website and Software.</span></p>
      <p style="text-align: justify;"><b><i>Beacons/Pixels:</i></b><span style="font-weight: 400;"> On our website and in our emails we use web beacons. When we send emails to Customers, we may track behaviour such as who opened the emails, who clicked the links and which pages of our Website they have visited. This allows us to measure the performance of our email campaigns and to improve our Website and Software. To do this, we may include single pixel, also called web beacons, in some emails we send. Web beacons allow us to collect information about when You open the email, Your IP address, Your browser or email client type, and other similar details. We also include Web Beacons in the emails we deliver for You. We use the data from those Web Beacons to create reports about how Your email campaign performed and what actions Your Contacts took. Reports are also available to us when we send email to You, so we may collect and review that information.</span></p>
      <p style="text-align: justify;"><b>ORDERRY may use aggregate, non-identifying statistical data for statistical analysis, marketing, or similar promotional purposes to help improve our offerings to You, to help diagnose any problems with our server and administer the Website and the Software or to improve Your browsing experience by personalizing the Website.</b><b></b></p>
      <p style="text-align: justify;"><b>Way of Your personal data protection</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We have implemented security policies and technical measures to protect the personal data that we collect, consistent with applicable privacy and security laws. These security measures are designed to prevent unauthorized access, improper use or disclosure, unauthorized modification, and unlawful destruction or accidental loss of Your personal data.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We operate a role-based access policy for personal data. What this means, is that an employee or any third party will only have access to personal data if they need that access to do their job.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We update and test our personal data privacy and security measures on an ongoing basis. We also provide training to our employees on privacy laws and how to comply with them and have disciplinary procedures in place that may be imposed on employees if they do not comply with our standards. We ensure that only employees who need to know Your personal data to fulfil the purposes of processing that personal data (as described in this Policy) have access to it.</span></p>
      <p style="text-align: justify;"><b>Ways of Your personal data sharing</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We take Your privacy seriously and will not share Your personal data with others, except in the following circumstances:</span></p>
      <p style="text-align: justify;"><b>Service providers and contractors</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may disclose Your personal data to third-party service providers to provide us with services such as website hosting and professional services, including information technology services, payroll services, auditing services, consultancy services, regulatory services, and legal services in other countries.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may use a third-party e-mail service provider to send e-mails to You. This service provider is prohibited from using Your e-mail address for any purpose other than to send ORDERRY related e-mail. Every time You receive an e-mail You will be provided the choice to opt-out of future e-mails by following the instructions provided in the e-mail.&nbsp;</span></p>
      <p style="text-align: justify;"><b>Our other group entities</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may disclose Your personal data to our other group entities in order to provide You with tailored services and communications, or in accordance with our business administrative practices.</span></p>
      <p style="text-align: justify;"><b>To fulfil Your option to share our website content with third parties</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">Using the sharing features on our Website (to share content with Facebook, LinkedIn, or Twitter, for example).</span></p>
      <p style="text-align: justify;"><b>Corporate transactions or events</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may disclose Your personal data to a third party in connection with a corporate reorganization, merger, joint venture, sale, transfer, or other disposition of all or any portion of our business or shares.</span></p>
      <p style="text-align: justify;"><b>Legal reasons</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We may use or disclose Your personal data as we deem necessary or appropriate under applicable laws; to respond to requests from public, governmental, and regulatory authorities; to comply with court orders, litigation procedures, and other legal processes; to obtain legal remedies or limit our damages; to protect the operations of our group entities; and to protect the rights, safety, or property of our employees, You, or others.</span></p>
      <p style="text-align: justify;"><b>International transfers of personal data</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">Some of our group entities and service providers are located in the United States (for example: Google Analytics). Accordingly, if You are an EU citizen/resident in the EU, please note that we will transfer Your personal data to the United States in accordance with EU data protection law requirements by using standard contractual clauses that have been approved by the European Commission. Such transfer may also be necessary in order to perform a contract with You/fulfil Your request and/or through obtaining Your explicit consent.</span></p>
      <p style="text-align: justify;"><b>Your rights with respect to Your personal data</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">If You are an EU citizen and reside in the EU, or are a non-EU national residing in the EU, You may have the following rights with respect to the personal data You provide to us, to the extent permitted by applicable data protection laws:</span></p>
      <ol style="list-style-type: lower-alpha; text-align: justify;">
        <li><span style="font-weight: 400;">to access or rectify Your personal data;</span></li>
        <li><span style="font-weight: 400;">to withdraw any consent that You have provided to us to process Your personal data;</span></li>
        <li><span style="font-weight: 400;">to have Your personal data erased if it is no longer necessary for the purposes for which it was processed, You have withdrawn Your consent to, or object to, its processing and there are no other legitimate grounds for processing it or You consider it has been unlawfully processed;</span></li>
        <li><span style="font-weight: 400;">to have the processing of Your personal data restricted if You contest its accuracy, its processing is unlawful, we no longer need it but You need it for a legal claim, or You have objected to its processing and await verification of our legitimate grounds for processing it;</span></li>
        <li><span style="font-weight: 400;">to have Your personal data transferred to another company under certain circumstances.</span></li>
        <li><span style="font-weight: 400;">to complain to Your national data protection regulator if You feel that Your personal data has been unlawfully processed.</span></li>
      </ol>
      <p style="text-align: justify;"><b>Term of Your personal data retaining</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">We retain Your personal data only for as long as is necessary for our relationship with You, in accordance with our retention policies, and in accordance with applicable laws. We do not collect more personal data than we need to fulfil our purposes stated in this Privacy Policy, and we will not retain it for longer than is necessary.</span></p>
      <p style="text-align: justify;"><b>Links to third-party sites</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">Our Website and Software may include links to other websites and (or) services operated by third parties. We are not responsible for information on these sites, nor for services or products offered by them, nor for their privacy practices. Use of such sites, including transmitting Your personal data to them, is at Your own risk. We encourage You to be aware when You leave our service and to read the privacy policies of any web service that collects personally identifiable information. Similarly, if You entered this Website and Software through another web service, we are also not responsible for the privacy practices of that service, and You should review this Privacy Policy before providing any personal data. This Privacy Policy applies solely to information collected by us.</span></p>
      <p style="text-align: justify;"><b>Data Security</b></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">ORDERRY endeavours to secure Your personal data from unauthorized access, use or disclosure by putting into place physical, electronic and managerial procedures to safeguard the information we collect through this Service. </span><span style="font-weight: 400;">All the information received via HTTPS is authenticated and encrypted with the help of 256-bit Secure Socket Layer (SSL) encryption. This state-of-the-art technology of encryption scrambles any information sent from Your computer to make it completely unintelligible in the case of interception. Anytime You are using a secure section of the Website, You will see a padlock on the screen of Your browser. This way You can be sure that You are using a secure link and all information is encrypted. </span><b>Credit card information is encrypted during transmission and payment processing is performed by a PCI compliant third-party processor and such information is not processed or retained by ORDERRY. </b><span style="font-weight: 400;">Other account information is accessible online only through the use of a password and data fields calling for personally identifying information are encrypted when in storage and in transmission. </span><span style="font-weight: 400;">Information collected </span><span style="font-weight: 400;">is stored on one or more secure database servers and cannot be accessed outside our corporate network.</span><span style="font-weight: 400;"> Only authorized ORDERRY’s employees, who perform technical support and are obligated by our privacy and security policies, have access to the information provided by our users.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">Please be aware, however, despite our efforts, no security measures are perfect or impenetrable, we cannot guarantee that unauthorized third parties will never be able to defeat those measures or use Your personal information for improper purposes.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">To protect the confidentiality of Your personal information, You must keep Your password confidential and not disclose it to any other person. You are responsible for all uses of the Service by any person using Your password. Please advise us immediately by emailing us at </span><span style="font-weight: 400;">help@orderry.com</span><span style="font-weight: 400;"> if You believe Your password has been misused. You should also note that email is not secure, and You should not send any confidential or sensitive information to us via an unsecured email.</span></p>
      <h2 style="text-align: justify;"><b>Change or removal of Personal Information</b></h2>
      <p style="text-align: justify;"><span style="font-weight: 400;">You can update or remove any or all Your personal information at any time by logging into Your ORDERRY account and editing Your personal information on the account settings page. You can view Your updated profile in order to confirm that Your edits have been made.</span></p>
      <p style="text-align: justify;"><span style="font-weight: 400;">If the personal information we've gathered from You changes or You no longer desire our services, we will update or remove any personal data You have previously provided to us. You can do this by sending a request to remove Your personal information to </span><span style="font-weight: 400;">help@orderry.com</span><span style="font-weight: 400;">.</span></p>
      <h2 style="text-align: justify;"><b>Changes or Updates</b></h2>
      <p style="text-align: justify;"><span style="font-weight: 400;">We reserve the right to change the provisions of this Privacy Policy at any time by posting a revised Privacy Policy on the Website and indicating on the Privacy Policy the date it was last updated. Your use of the Service following the posting of such changes or revised statement shall constitute Your acceptance of any such changes. We encourage You to review this Policy whenever You use our Website and Software to determine if any changes have been made and to make sure that You understand how any personal data You provide will be used.</span></p>
      <h2 style="text-align: justify;"><b>Contacts&nbsp;</b></h2>
      <p style="text-align: justify;"><span style="font-weight: 400;">If You have any questions or comments about this Policy or the practices relating to these Website or/ and Program, or You wish to verify, correct or delete any personal information we have collected, please contact us at </span><span style="font-weight: 400;">help@orderry.com</span><span style="font-weight: 400;">.</span></p>
    </div>
  </div>
 </template>

<style scoped>

</style>